# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heidi
email: heidi@example.com
logo: /public/image/logo.png
tagline: 'A Jekyll theme'
description: >- # this means to ignore newlines until "baseurl:"
  A <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme based on 
  <a href="https://github.com/poole/hyde" target="_blank">Hyde</a>. 
  Made by <a href="https://twitter.com/petoem" target="_blank">@petoem</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-gist
  - jekyll-paginate

include:
  - _pages
  - _images

# Permalinks
permalink: pretty

# i18n - jekyll-polyglot settings
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["public"]

# dev settings TODO: remove
# jekyll-minifier:
#   exclude: '*.html'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

paginate: 1
paginate_path: /blog/page-:num/
